version: '3.7'
services:
  mysql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=homework
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=qwerty123